import * as React from 'react';

import { Landing } from '../../context';

import NavBar from '../../components/Navbar/Navbar';
import Article from '../../components/Article/Article';
import { ILink } from '../../../typing/component-details';

export default class TermsConditions extends React.Component<{links: Array<ILink>}>{

  render() {
    return (
      <>
        <section id="jumb">
          <div className="preview">
            <NavBar
              brand={Landing.brand}
              links={this.props.links}
              imageLinks={[Landing.buttonsStore[0]]}
              classNavBrand={'navbar-brand'}
            />
            <div className="container" style={{ paddingBottom: '60px' }}>
              <Article
                title="Terms and Conditions"
                style={{ color: 'white' }}
              />
            </div>
          </div>
        </section>
        <section className='document container'>
          <div className="text-center">
            <h3>MOBILE APPLICATION TERMS OF USE</h3>
            <h3>VERSION 1.0</h3>
            <h3>LAST REVISED ON: ________________, 20___</h3>
          </div>
          <p>By creating an Account (as defined herein), using any of the services offered by Bramti, Inc. (“Company”, “us”, “our”, “ours”, and “we”) titled “Bramti Connect” through a mobile device, mobile application or computer (collectively, the “Service”) the end user (“you”, “your” and “yours”)  agree to be by bound by these Terms of Use (“Terms”) and our Privacy Policy (“Privacy Policy”), incorporated by reference into these Terms. Certain features of the Service may be subject to additional guidelines, terms, or rules in connection with such features, which will be posted on the mobile application (“App”) by which you access the Service.  All such additional terms, guidelines, and rules are incorporated by reference into these Terms.</p>
          <p className='text-uppercase'>THESE TERMS SET FORTH THE LEGALLY BINDING TERMS AND CONDITIONS THAT GOVERN YOUR USE OF THE SERVICE.  BY ACCESSING OR USING THE APP AND ANY OF ITS SERVICES, YOU ARE ACCEPTING THESE TERMS (ON BEHALF OF YOURSELF OR THE ENTITY THAT YOU REPRESENT), AND YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, AUTHORITY, AND CAPACITY TO ENTER INTO THESE TERMS (ON BEHALF OF YOURSELF OR THE ENTITY THAT YOU REPRESENT).  YOU MAY NOT ACCESS OR USE THE APP OR SERVICES OR ACCEPT THE TERMS IF YOU ARE NOT AT LEAST 13 YEARS OLD.  IF YOU ARE UNDER THE AGE OF 18, YOU MAY BE RESTRICTED FROM ACCESS TO CERTAIN SERVICES IN THE COMPANY’S SOLE DISCRETION. IF YOU DO NOT AGREE WITH ALL OF THE PROVISIONS OF THESE TERMS, DO NOT ACCESS AND/OR USE THE APP.</p>
          <p  className='text-uppercase'>THESE TERMS REQUIRE THE USE OF ARBITRATION (SECTION 10.2) ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES, RATHER THAN JURY TRIALS OR CLASS ACTIONS, AND ALSO LIMIT THE REMEDIES AVAILABLE TO YOU IN THE EVENT OF A DISPUTE.</p>
          <h3 className='text-left'>1.	ACCOUNTS</h3>
          <p><span className='text-bold block-offset-1'>1.1	Account Creation.</span>In order to access the Service, you must register for an account (“Account”) and provide certain information about yourself as prompted by the account registration form.  You represent and warrant that: (a) all required registration information you submit is truthful and accurate; (b) you will maintain the accuracy of such information; (c) you have never been convicted of or pled no contest to a felony, a sex crime, or any crime involving violence, and that you are not required to register as a sex offender with any state, federal, or local sex offender registry; (d) you will comply with these Terms and all applicable local, state, national, and international laws, rules, and regulations; and (e) though we do not currently conduct background screenings, you shall not object to our conduct of criminal background checks of available public records to confirm your compliance with these Terms. You may delete your Account at any time, for any reason, by following the instructions on the App.  Company may suspend or terminate your Account in accordance with Section 8. </p>
          <p><span className='text-bold block-offset-1'>1.2	Account Responsibilities.</span> You are responsible for maintaining the confidentiality of your Account login information and are fully responsible for all activities that occur under your Account.  You agree to immediately notify Company of any unauthorized use or suspected unauthorized use of your Account or any other breach of security.  Company cannot and will not be liable for any loss or damage arising from your failure to comply with the above requirements including without limitation stalking, defamation, CAN-SPAM violations, and other criminal or civil misconduct by other users or third parties.</p>
          <p><span className='text-bold block-offset-1'>1.3  Geographic Limitations.</span>
           The Services herein are intended for use by residents of the United States and those residents of non-U.S. countries who are not located in, under the control of, or a national or resident of any country which the United States has (i) embargoed goods; (ii) identified as a Specially Designated National, or (iii) placed on any restrictions by the U.S. Department of Commerce. To the extent that use of the App or its Services is not legal in your jurisdiction, you are prohibited from using the App or its Services.
          </p>
           <h3 className='text-left'>2.	ACCESS TO THE APP </h3>
          <p><span className='text-bold block-offset-1'>2.1	License.</span> Subject to these Terms, Company grants you a non-transferable, non-exclusive, revocable, limited license to use and access the App and its Services solely for your own personal, noncommercial use.
         </p>
             <p><span className='text-bold block-offset-1'>2.2	Certain Restrictions.</span>  The rights granted to you in these Terms are subject to the following restrictions: (a) you shall not license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the App, whether in whole or in part, or any content displayed on the App; (b) you shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the App; (c) you shall not access the App in order to build a similar or competitive mobile application, website, product, or service in any medium now known or hereafter devised; and (d) except as expressly stated herein, no part of the App may be copied, reproduced, distributed, republished, downloaded, displayed, posted, or transmitted in any form or by any means.  Unless otherwise indicated, any future release, update, or other addition to functionality of the App shall be subject to these Terms.  All copyright and other proprietary notices on the App (or on any content displayed on the App) must be retained on all copies thereof.</p>
          <p><span className='text-bold block-offset-1'>2.3	Modification.</span> Company reserves the right, at any time, to modify, suspend, or discontinue the App and any of its Services (in whole or in part) with or without notice to you.  You agree that Company will not be liable to you or to any third-party for any modification, suspension, or discontinuation of the App, any part thereof, or Services therein.</p>
          <p><span className='text-bold block-offset-1'>2.4	No Support or Maintenance.</span> You acknowledge and agree that Company will have no obligation to provide you with any support or maintenance in connection with the App or any of its Services.</p>
          <p><span className='text-bold block-offset-1'>2.5	Ownership.</span> Excluding any User Content that you may provide (defined below), you acknowledge that all the intellectual property rights, including copyrights, patents, trademarks, and trade secrets, in the App and its content are owned by Company or Company’s suppliers.  Neither these Terms (nor your access to the App) transfers to you or any third party any rights, title or interest in or to such intellectual property rights, except for the limited access rights expressly set forth in Section 2.1. Company and its suppliers reserve all rights not granted in these Terms.  There are no implied licenses granted under these Terms.</p>
          <p><span className='text-bold block-offset-1'>2.6	Payment.</span>Company offers auto-renewing subscriptions to the Services offered in the App through iTunes and/or Apple’s App Store (“Subscriptions”) and avails you to consumables through in-app purchases (“In-App Purchases”). If you Subscription, you will continue to be billed for the subscription until you cancel. After your initial subscription commitment period, and again after any subsequent subscription period, your Subscription will automatically renew for an additional equivalent period, at the price you agreed to when subscribing. If you do not wish your Subscription to renew, log in to iTunes and/or Apple’s App Store and follow instructions to cancel your Subscription, even if you have otherwise deleted the App from your device. Deleting your account on the App may not result in the cancellation of your subscription. Company will retain all funds charged to you unless and until you cancel your Subscriptions. Upon cancellation, you may use the Service until the end of your then-current Subscription term, and your Subscription will not be renewed after your then-current term expires. Your Subscription shall be governed by the terms set forth in the Apple Media Services Terms and Conditions (available at https://www.apple.com/legal/internet-services/itunes/us/terms.html). Specifically, Subscription cancellation terms through Apple are available at https://support.apple.com/en-us/HT202039. Changes to Subscription pricing are also governed by the Apple Media Services Terms and Conditions, which is incorporated by reference herein. Changes to the Apple Media Services Terms and Conditions are governed by those terms, and because they are incorporated herein by reference, changes therein may cause material changes to this Agreement without notification from us. Refunds are exclusively handled through Apple. If you wish to request a refund, please visit https://getsupport.apple.com.</p>
          <p>All In-App Purchases must be conducted through iTunes and/or Apple’s App Store. Pursuant to the terms of the Apple Media Services Terms and Conditions, you will be required to authenticate your account before making In-App Purchases – separate from any authentication to obtain other content – by entering your password or using Touch ID or Face ID. You will be able to make additional In-App Purchases for fifteen minutes without re-authenticating unless you have asked Apple to require a password for every purchase or have enabled Touch ID or Face ID. You can turn off the ability to make In-App Purchases by following instructions available through Apple at https://support.apple.com/en-us/HT201304. </p>
        <h3 className='text-left'>3.	USER CONTENT </h3>
          <p><span className='text-bold block-offset-1'>3.1	User Content</span>.  “User Content” means any and all information and content that a user submits to, or uses with, the App or its Services (e.g., content in the user’s profile or postings).  You are solely responsible for your User Content.  You assume all risks associated with use of your User Content, including any reliance on its accuracy, completeness, or usefulness by others, or any disclosure of your User Content that personally identifies you or any third party, and activities by other users or third-parties including without limitation unlawful interactions, fraud, deceit, violent acts (e.g., sexual assault, assault, battery, robbery, rape, murder, manslaughter), harassment of any kind (e.g., sexual harassment, racial harassment, defamatory conduct), .  You hereby represent and warrant that your User Content does not violate our Acceptable Use Policy (defined in Section 3.3).  You may not represent or imply to others that your User Content is in any way provided, sponsored or endorsed by Company.  Because you alone are responsible for your User Content, you may expose yourself to liability if, for example, your User Content violates the Acceptable Use Policy.  Company is not obligated to backup any User Content, and your User Content may be deleted at any time without prior notice.  You are solely responsible for creating and maintaining your own backup copies of your User Content if you desire. Our license to User Content is subject to your rights under applicable law (for example laws regarding personal data protection to the extent any User Content contains personal information as defined by those laws) and is for the limited purpose of operating, developing, providing, and improving the Service and researching and developing new ones.</p>
          <p><span className='text-bold block-offset-1'>3.2	License.  </span>You hereby grant (and you represent and warrant that you have the right to grant) to Company an irrevocable, nonexclusive, royalty-free and fully paid, worldwide license to reproduce, distribute, publicly display and perform, prepare derivative works of, incorporate into other works, and otherwise use and exploit your User Content, and to grant sublicenses of the foregoing rights, solely for the purposes of including your User Content in the App.  You hereby irrevocably waive (and agree to cause to be waived) any claims and assertions of moral rights or attribution with respect to your User Content. You authorize us to act on your behalf with respect to infringing uses of User Content taken from the Service by other users or third parties. This expressly includes the authority, but not the obligation, to send notice pursuant to the Digital Millennium Copyright Act (17 U.S.C. 512(c)(3)) on your behalf if User Content is taken and used by third parties outside of the Service. You agree that any User Content you place or that you authorize us to place on the Service or anywhere in the App may be viewed by other users and may be viewed by any person visiting or participating in the Service. </p>
          <p><span className='text-bold block-offset-1'>3.3	Acceptable Use Policy.</span>  The following terms constitute our “Acceptable Use Policy”:</p>
          <p><span className='text-bold block-offset-2'>(a)</span>	You agree not to use the App or any of its Services to collect, upload, transmit, display, or distribute any User Content (i) that violates any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (ii) that is unlawful, harassing, abusive, tortious, threatening, harmful, invasive of another’s privacy, vulgar, defamatory, false, intentionally misleading, trade libelous, pornographic, obscene, patently offensive, promotes racism, bigotry, hatred, or physical harm of any kind against any group or individual or is otherwise objectionable; (iii) that is harmful to minors in any way; (iv) that attempts to spam, solicit money, or defraud other users; (v) that impersonates any person or entity or post images of another person without authority; (vi) that solicits passwords for any purpose, or personal identifying information for commercial or unlawful purposes from other users or disseminates another person’s personal information without their permission; or (vii) that is in violation of any law, regulation, or obligations or restrictions imposed by any third party. </p>
          <p><span className='text-bold block-offset-2'>(b)</span>	In addition, you agree not to: (i) upload, transmit, or distribute to or through the App any computer viruses, worms, or any software intended to damage or alter a computer system or data; (ii) send through the App or through use of any of its Services unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of duplicative or unsolicited messages, whether commercial or otherwise; (iii)  use the App or access to the Services to harvest, collect, gather or assemble information or data regarding other users, including e-mail addresses, without their consent; (iv) interfere with, disrupt, or create an undue burden on servers or networks connected to the App, or violate the regulations, policies or procedures of such networks; (v) attempt to gain unauthorized access to the App (or to other devices or networks connected to or used together with the App or Services), whether through password mining or any other means; (vi) harass or interfere with any other user’s use and enjoyment of the App; or (vi) use software or automated agents or scripts to produce multiple accounts on the App, or to generate automated searches, requests, or queries to (or to strip, scrape, or mine data from) the App (provided, however, that we conditionally grant to the operators of public search engines revocable permission to use spiders to copy materials from the App for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials, subject to the parameters set forth in our robots.txt file).</p>
          <p><span className='text-bold block-offset-1'>3.4	Enforcement.</span> We reserve the right (but have no obligation) to review any User Content, and to investigate and/or take appropriate action against you in our sole discretion if you violate the Acceptable Use Policy or any other provision of these Terms; otherwise create liability for us or any other person; or merely behave in a manner that we believe violates the spirit of the Acceptable Use Policy and is generally deemed inappropriate by us. Such action may include removing or modifying your User Content, terminating your Account in accordance with Section 8, and/or reporting you to law enforcement authorities.</p>
          <p><span className='text-bold block-offset-1'>3.5	Feedback.</span> If you provide Company with any feedback or suggestions regarding the Services or the App (“Feedback”), you hereby assign to Company all rights in such Feedback and agree that Company shall have the right to use and fully exploit such Feedback and related information in any manner it deems appropriate.  Company will treat any Feedback you provide to Company as non-confidential and non-proprietary.  Feedback shall not include specific complaints, warnings, concerns, or other issues regarding your personal safety (“Alerts”). You agree that you will not submit to Company any information or ideas that you consider to be confidential or proprietary. You further agree that Company may access, preserve, and disclose your account information and User Content, if required to do so by law or in a good faith belief that such access, preservation, or disclosure is reasonably necessary, such as to: (i) comply with legal process; (ii) enforce these Terms; (iii) respond to claims that any User Content violates the rights of third-parties; (iv) respond to Alerts by you, other users, or third-parties; or (v) protect the rights, property, or personal safety of the Company or any other person.</p>
          <p><span className='text-bold'>4.	INDEMNIFICATION.</span> You agree to indemnify and hold Company (and its officers, employees, and agents) harmless, including costs and attorneys’ fees, from any claim or demand made by any third party due to or arising out of (a) your use of the Services, (b) your violation of these Terms, (c) your violation of applicable laws or regulations, (d) your conduct on or off the App, or (e) your User Content.  Company reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims.  You agree not to settle any matter without the prior written consent of Company.  Company will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.</p>
           <h3 className='text-left'>5.	THIRD-PARTY LINKS & ADS; OTHER USERS</h3>
          <p><span className='text-bold'>5.1	Third-Party Links & Ads.</span>  The App may contain links to third-party websites, mobile applications, and services, and/or display advertisements for third parties (collectively, “Third-Party Links & Ads”).  Such Third-Party Links & Ads are not under the control of Company, and Company is not responsible for any Third-Party Links & Ads.  Company provides access to these Third-Party Links & Ads only as a convenience to you, and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Links & Ads.  You use all Third-Party Links & Ads at your own risk and should apply a suitable level of caution and discretion in doing so. When you click on any of the Third-Party Links & Ads, the applicable third party’s terms and policies apply, including the third party’s privacy and data gathering practices.  You should make whatever investigation you feel necessary or appropriate before proceeding with any transaction in connection with such Third-Party Links & Ads.</p>
          <p><span className='text-bold'>5.2	Other Users.</span>  Each user is solely responsible for any and all of its own User Content.  Because we do not control User Content, you acknowledge and agree that we are not responsible for any User Content, whether provided by you or by others.  We make no guarantees regarding the accuracy, currency, suitability, or quality of any User Content.  Your interactions with other users are solely between you and such users.  You agree that Company will not be responsible for any loss or damage incurred as the result of any such interactions whether occurring on the App or offline.  If there is a dispute between you and any other user, we are under no obligation to become involved.</p>
          <p><span className='text-bold'>5.3	Release.</span>  You hereby release and forever discharge the Company (and our officers, employees, agents, successors, and assigns) from, and hereby waive and relinquish, each and every past, present and future dispute, claim, controversy, demand, right, obligation, liability, action and cause of action of every kind and nature (including personal injuries, death, and property damage), that has arisen or arises directly or indirectly out of, or that relates directly or indirectly to, the Services (including any interactions with, or act or omission of, other users or any Third-Party Links & Ads).  IF YOU ARE A CALIFORNIA RESIDENT, YOU HEREBY WAIVE CALIFORNIA CIVIL CODE SECTION 1542 IN CONNECTION WITH THE FOREGOING, WHICH STATES: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.”</p>
          
           <h3 className='text-left'>6.	DISCLAIMERS </h3>
           <p>THE SERVICES PROVIDED HEREIN ARE SO PROVIDED ON AN “AS-IS” AND “AS AVAILABLE” BASIS, AND COMPANY (AND OUR SUPPLIERS) EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING ALL WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, ACCURACY, OR NON-INFRINGEMENT.  WE (AND OUR SUPPLIERS) MAKE NO WARRANTY THAT THE APP OR ANY OF ITS SERVICES WILL MEET YOUR REQUIREMENTS, WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS, OR WILL BE ACCURATE, RELIABLE, FREE OF VIRUSES OR OTHER HARMFUL CODE, COMPLETE, LEGAL, OR SAFE.  IF APPLICABLE LAW REQUIRES ANY WARRANTIES WITH RESPECT TO THE APP, ALL SUCH WARRANTIES ARE LIMITED IN DURATION TO NINETY (90) DAYS FROM THE DATE OF FIRST USE.</p>
           <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.  SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.  </p>
           <h3 className='text-left'>7.	LIMITATION ON LIABILITY </h3>
           <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL COMPANY (OR OUR SUPPLIERS) BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFITS, LOST DATA, COSTS OF PROCUREMENT OF SUBSTITUTE PRODUCTS, OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING FROM OR RELATING TO THESE TERMS OR YOUR USE OF, OR INABILITY TO USE, THE SERVICES, EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  ACCESS TO, AND USE OF, THE APP OR ANY OF ITS SERVICES IS AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PERSON, DEVICE OR COMPUTER SYSTEM, OR LOSS RESULTING THEREFROM</p>
           <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY DAMAGES ARISING FROM OR RELATED TO THIS AGREEMENT (FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION), WILL AT ALL TIMES BE LIMITED TO A MAXIMUM OF FIFTY US DOLLARS (U.S. $50). THE EXISTENCE OF MORE THAN ONE CLAIM WILL NOT ENLARGE THIS LIMIT.  YOU AGREE THAT OUR SUPPLIERS WILL HAVE NO LIABILITY OF ANY KIND ARISING FROM OR RELATING TO THIS AGREEMENT.</p>
           <p>SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.   </p>
          <p><span className='text-bold'>8.	TERM AND TERMINATION.</span>   Subject to this Section, these Terms will remain in full force and effect while you use the App or any of its Services.  We may suspend or terminate your rights to use the App or any of its Services (including your Account) at any time for any reason at our sole discretion, including for any use of the App or its Services in violation of these Terms.  Upon termination of your rights under these Terms, your Account and right to access and use the App or any of its Services will terminate immediately.  You understand that any termination of your Account may involve deletion of your User Content associated with your Account from our live databases.  Company will not have any liability whatsoever to you for any termination of your rights under these Terms, including for termination of your Account or deletion of your User Content.  Even after your rights under these Terms are terminated, the following provisions of these Terms will remain in effect: Sections 2.2 through 2.5, Section 3 and Sections 4 through 10.</p>
           <h3 className='text-left'>9.	INTELLECTUAL PROPERTY POLICY. </h3>
           <p>Company respects the intellectual property and goodwill of others and asks that users of our App and related Services do the same.  In connection with our App, we have adopted and implemented a policy respecting trademark, copyright and any other law governing the intangible property that provides for the removal of any unlawful, infringing, “passing off” (either of name, likeness, or other confusingly similar identifying materials), or otherwise anti-competitive materials and for the termination, in appropriate circumstances, of users of our App who are repeat infringers of intellectual and intangible property rights.  If you believe that one of our users is, through the use of our App, unlawfully infringing upon your intangible or intellectual property rights, and wish to have the allegedly infringing material removed, the following information in the form of a written notification must be provided to the company:</p>
           <div className="block-offset-1">
            <p>Bramti, Inc.</p>
            <p>113 Cherry Street</p>
            <p>Seattle, WA 98104</p>
            <p>support@bramti.com</p>
          </div>
           <h3 className='text-left'>10.	GENERAL</h3>
          <p><span className='text-bold block-offset-1'>10.1	Changes.</span>  These Terms are subject to occasional revision, and if we make any substantial changes, we may notify you by sending you an e-mail to the last e-mail address you provided to us (if any), and/or by prominently posting notice of the changes in our App or via push notification, if so enabled on your device.  You are responsible for providing us with your most current e-mail address, accessing the App, or enabling push notifications on your device.  In the event that the last e-mail address that you have provided us is not valid, or for any reason Company is not capable of delivering to you the notice described above, our dispatch of the e-mail containing such notice or prominent display of such changes on the App will nonetheless constitute effective notice of the changes described in the notice.  Any changes to these Terms will be effective upon the earlier of thirty (30) calendar days following our dispatch of an e-mail notice to you (if applicable) or thirty (30) calendar days following our posting of notice of the changes on our App or push notification sent from our App.  These changes will be effective immediately for new users of our App or the Services therein.  Continued use of our App or the Services therein following notice of such changes shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes.</p>
          <p><span className='text-bold block-offset-1'>10.2	Dispute Resolution. Please read this Arbitration Agreement carefully.  It is part of your contract with Company and affects your rights.  It contains procedures for MANDATORY BINDING ARBITRATION AND A CLASS ACTION WAIVER.</span></p>
          <p><span className='text-bold block-offset-2'>(a)</span>	Applicability of Arbitration Agreement.  All claims and disputes (excluding claims for injunctive or other equitable relief as set forth below) in connection with the Terms or the use of any product or service provided by the Company that cannot be resolved informally or in small claims court shall be resolved by binding arbitration on an individual basis under the terms of this Arbitration Agreement.  Unless otherwise agreed to, all arbitration proceedings shall be held in English.  This Arbitration Agreement applies to you and the Company, and to any subsidiaries, affiliates, agents, employees, predecessors in interest, successors, and assigns, as well as all authorized or unauthorized users or beneficiaries of services or goods provided under the Terms.</p>
          <p><span className='text-bold block-offset-2'>(b)</span>	Notice Requirement and Informal Dispute Resolution.  Before either party may seek arbitration, the party must first send to the other party a written Notice of Dispute (“Notice”) describing the nature and basis of the claim or dispute, and the requested relief.  A Notice to the Company should be sent to 113 Cherry Street, Seattle, WA 98104.  After the Notice is received, you and the Company may attempt to resolve the claim or dispute informally.  If you and the Company do not resolve the claim or dispute within thirty (30) days after the Notice is received, either party may begin an arbitration proceeding.  The amount of any settlement offer made by any party may not be disclosed to the arbitrator until after the arbitrator has determined the amount of the award, if any, to which either party is entitled.</p>
          <p><span className='text-bold block-offset-2'>(c)</span>	Arbitration Rules.  Arbitration shall be initiated through the American Arbitration Association (“AAA”), an established alternative dispute resolution provider (“ADR Provider”) that offers arbitration as set forth in this section.  If AAA is not available to arbitrate, the parties shall agree to select an alternative ADR Provider.  The rules of the ADR Provider shall govern all aspects of the arbitration, including but not limited to the method of initiating and/or demanding arbitration, except to the extent such rules are in conflict with the Terms.  The AAA Consumer Arbitration Rules (“Arbitration Rules”) governing the arbitration are available online at www.adr.org or by calling the AAA at 1-800-778-7879.  The arbitration shall be conducted by a single, neutral arbitrator.  Any claims or disputes where the total amount of the award sought is less than Ten Thousand U.S. Dollars (US $10,000.00) may be resolved through binding non-appearance-based arbitration, at the option of the party seeking relief.  For claims or disputes where the total amount of the award sought is Ten Thousand U.S. Dollars (US $10,000.00) or more, the right to a hearing will be determined by the Arbitration Rules.  Any hearing will be held in a location within 100 miles of your residence, unless you reside outside of the United States, and unless the parties agree otherwise.  If you reside outside of the U.S., the arbitrator shall give the parties reasonable notice of the date, time and place of any oral hearings. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.  If the arbitrator grants you an award that is greater than the last settlement offer that the Company made to you prior to the initiation of arbitration, the Company will pay you the greater of the award or $2,500.00.  Each party shall bear its own costs (including attorney’s fees) and disbursements arising out of the arbitration and shall pay an equal share of the fees and costs of the ADR Provider.</p>
          <p><span className='text-bold block-offset-2'>(d)</span>	Additional Rules for Non-Appearance Based Arbitration.  If non-appearance-based arbitration is elected, the arbitration shall be conducted by telephone, online and/or based solely on written submissions; the specific manner shall be chosen by the party initiating the arbitration.  The arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise agreed by the parties.</p>
          <p><span className='text-bold block-offset-2'>(e)</span>	Time Limits.  If you or the Company pursue arbitration, the arbitration action must be initiated and/or demanded within the statute of limitations (i.e., the legal deadline for filing a claim) and within any deadline imposed under the AAA Rules for the pertinent claim.</p>
          <p><span className='text-bold block-offset-2'>(f)</span>	Authority of Arbitrator.  If arbitration is initiated, the arbitrator will decide the rights and liabilities, if any, of you and the Company, and the dispute will not be consolidated with any other matters or joined with any other cases or parties.  The arbitrator shall have the authority to grant motions dispositive of all or part of any claim.  The arbitrator shall have the authority to award monetary damages, and to grant any non-monetary remedy or relief available to an individual under applicable law, the AAA Rules, and the Terms.  The arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded.  The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have.  The award of the arbitrator is final and binding upon you and the Company.</p>
          <p><span className='text-bold block-offset-2'>(g)</span>	Waiver of Jury Trial.  THE PARTIES HEREBY WAIVE THEIR CONSTITUTIONAL AND STATUTORY RIGHTS TO GO TO COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY, instead electing that all claims and disputes shall be resolved by arbitration under this Arbitration Agreement.  Arbitration procedures are typically more limited, more efficient and less costly than rules applicable in a court and are subject to very limited review by a court.  In the event any litigation should arise between you and the Company in any state or federal court in a suit to vacate or enforce an arbitration award or otherwise, YOU AND THE COMPANY WAIVE ALL RIGHTS TO A JURY TRIAL, instead electing that the dispute be resolved by a judge.</p>
          <p><span className='text-bold block-offset-2'>(h)</span>	Waiver of Class or Consolidated Actions.  ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED OR LITIGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS BASIS, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR LITIGATED JOINTLY OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER.  </p>
          <p><span className='text-bold block-offset-2'>(i)</span>	Confidentiality.  All aspects of the arbitration proceeding, including but not limited to the award of the arbitrator and compliance therewith, shall be strictly confidential.  The parties agree to maintain confidentiality unless otherwise required by law.  This paragraph shall not prevent a party from submitting to a court of law any information necessary to enforce this Agreement, to enforce an arbitration award, or to seek injunctive or equitable relief.</p>
          <p><span className='text-bold block-offset-2'>(j)</span>	Severability.  If any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable by a court of competent jurisdiction, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Agreement shall continue in full force and effect.</p>
          <p><span className='text-bold block-offset-2'>(k)</span>	Right to Waive.  Any or all of the rights and limitations set forth in this Arbitration Agreement may be waived by the party against whom the claim is asserted.  Such waiver shall not waive or affect any other portion of this Arbitration Agreement.</p>
          <p><span className='text-bold block-offset-2'>(l)</span>	Survival of Agreement.  This Arbitration Agreement will survive the termination of your relationship with Company.  </p>
          <p><span className='text-bold block-offset-2'>(m)</span>	Small Claims Court.  Notwithstanding the foregoing, either you or the Company may bring an individual action in small claims court.</p>
          <p><span className='text-bold block-offset-2'>(n)</span>	Emergency Equitable Relief.  Notwithstanding the foregoing, either party may seek emergency equitable relief before a state or federal court in order to maintain the status quo pending arbitration.  A request for interim measures shall not be deemed a waiver of any other rights or obligations under this Arbitration Agreement.</p>
          <p><span className='text-bold block-offset-2'>(o)</span>	Claims Not Subject to Arbitration.  Notwithstanding the foregoing, claims of defamation, violation of the Computer Fraud and Abuse Act, and infringement or misappropriation of the other party’s patent, copyright, trademark or trade secrets shall not be subject to this Arbitration Agreement.</p>
          <p><span className='text-bold block-offset-2'>(p)</span>	Courts.  In any circumstances where the foregoing Arbitration Agreement permits the parties to litigate in court, the parties hereby agree to submit to the personal jurisdiction of the courts located within King County, Washington, for such purpose </p>
          <p><span className='text-bold block-offset-1'>10.3	Export.</span> The App and its Services may be subject to U.S. export control laws and may be subject to export or import regulations in other countries. You agree not to export, reexport, or transfer, directly or indirectly, any U.S. technical data acquired from Company, or any products utilizing such data, in violation of the United States export laws or regulations. </p>
          <p><span className='text-bold block-offset-1'>10.4	Disclosures.</span>  Company is located at the address in Section 10.8. If you are a Washington State resident, you may report complaints to the Attorney General’s Office, Consumer Resource Center, 800 Fifth Avenue, Suite 2000, Seattle, WA 98104, or by telephone at 1-800-551-4636 (Washington Only) or 206-464-6684 (outside of Washington).</p>
          <p><span className='text-bold block-offset-1'>10.6	Entire Terms.</span> These Terms constitute the entire agreement between you and us regarding the use of the App or any of its Services. Our failure to exercise or enforce any right or provision of these Terms shall not operate as a waiver of such right or provision. The section titles in these Terms are for convenience only and have no legal or contractual effect. The word “including” means “including without limitation”.  If any provision of these Terms is, for any reason, held to be invalid or unenforceable, the other provisions of these Terms will be unimpaired, and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law.  Your relationship to Company is that of an independent contractor, and neither party is an agent or partner of the other.  These Terms, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without Company’s prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void.  Company may freely assign these Terms.  The terms and conditions set forth in these Terms shall be binding upon assignees. </p>
          <p><span className='text-bold block-offset-1'>10.7	Copyright/Trademark Information.</span>  Copyright © 2019 Bramti, Inc. All rights reserved.  All trademarks, logos and service marks (“Marks”) displayed on the App are our property or the property of other third parties. You are not permitted to use these Marks without our prior written consent or the consent of such third party which may own the Marks.</p>
          <p><span className='text-bold block-offset-1'>10.8	Contact Information:</span></p>
          <div className="block-offset-1">
            <p>Bramti, Inc.</p>
            <p>113 Cherry Street</p>
            <p>Seattle, WA 98104</p>
            <p>support@bramti.com</p>
          </div>
        </section>
      </>
    );
  }
}
